//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinanceTracker.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Budget.
        /// </summary>
        public static string Button_Budget {
            get {
                return ResourceManager.GetString("Button_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Charts.
        /// </summary>
        public static string Button_Charts {
            get {
                return ResourceManager.GetString("Button_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clear.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Down.
        /// </summary>
        public static string Button_Down {
            get {
                return ResourceManager.GetString("Button_Down", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expenses.
        /// </summary>
        public static string Button_Expenses {
            get {
                return ResourceManager.GetString("Button_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open Github.
        /// </summary>
        public static string Button_OpenGithub {
            get {
                return ResourceManager.GetString("Button_OpenGithub", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Filters.
        /// </summary>
        public static string Button_ShowFilters {
            get {
                return ResourceManager.GetString("Button_ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sort Amount.
        /// </summary>
        public static string Button_SortAmount {
            get {
                return ResourceManager.GetString("Button_SortAmount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sort Category.
        /// </summary>
        public static string Button_SortCategory {
            get {
                return ResourceManager.GetString("Button_SortCategory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sort Date.
        /// </summary>
        public static string Button_SortDate {
            get {
                return ResourceManager.GetString("Button_SortDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sort Name.
        /// </summary>
        public static string Button_SortName {
            get {
                return ResourceManager.GetString("Button_SortName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Up.
        /// </summary>
        public static string Button_Up {
            get {
                return ResourceManager.GetString("Button_Up", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All.
        /// </summary>
        public static string Category_All {
            get {
                return ResourceManager.GetString("Category_All", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bills.
        /// </summary>
        public static string Category_Bills {
            get {
                return ResourceManager.GetString("Category_Bills", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Entertainment.
        /// </summary>
        public static string Category_Entertainment {
            get {
                return ResourceManager.GetString("Category_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Food.
        /// </summary>
        public static string Category_Food {
            get {
                return ResourceManager.GetString("Category_Food", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Other.
        /// </summary>
        public static string Category_Other {
            get {
                return ResourceManager.GetString("Category_Other", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transport.
        /// </summary>
        public static string Category_Transport {
            get {
                return ResourceManager.GetString("Category_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Current expenses exceed the new budget limit..
        /// </summary>
        public static string Dialog_BudgetAlert2Message {
            get {
                return ResourceManager.GetString("Dialog_BudgetAlert2Message", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Budget Alert.
        /// </summary>
        public static string Dialog_BudgetAlert2Title {
            get {
                return ResourceManager.GetString("Dialog_BudgetAlert2Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Budget has been exceeded!.
        /// </summary>
        public static string Dialog_BudgetAlertMessage {
            get {
                return ResourceManager.GetString("Dialog_BudgetAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Switch language? Application will restart..
        /// </summary>
        public static string Dialog_ChangeLanguageMessage {
            get {
                return ResourceManager.GetString("Dialog_ChangeLanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change Language.
        /// </summary>
        public static string Dialog_ChangeLanguageTitle {
            get {
                return ResourceManager.GetString("Dialog_ChangeLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Switch theme? Application will restart..
        /// </summary>
        public static string Dialog_ChangeThemeMessege {
            get {
                return ResourceManager.GetString("Dialog_ChangeThemeMessege", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change Theme.
        /// </summary>
        public static string Dialog_ChangeThemeTitle {
            get {
                return ResourceManager.GetString("Dialog_ChangeThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu This will permanently delete all expenses. Continue?.
        /// </summary>
        public static string Dialog_ClearDataMessage {
            get {
                return ResourceManager.GetString("Dialog_ClearDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clear Data.
        /// </summary>
        public static string Dialog_ClearDataTitle {
            get {
                return ResourceManager.GetString("Dialog_ClearDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You have unsaved changes. Exit anyway?.
        /// </summary>
        public static string Dialog_UnsavedChangesMessage {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unsaved Changes.
        /// </summary>
        public static string Dialog_UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Budget Alert.
        /// </summary>
        public static string DialogBudgedAlertTitle {
            get {
                return ResourceManager.GetString("DialogBudgedAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amount.
        /// </summary>
        public static string Header_Amount {
            get {
                return ResourceManager.GetString("Header_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category.
        /// </summary>
        public static string Header_Category {
            get {
                return ResourceManager.GetString("Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date.
        /// </summary>
        public static string Header_Date {
            get {
                return ResourceManager.GetString("Header_Date", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu _About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change _Language.
        /// </summary>
        public static string Menu_ChangeLanguage {
            get {
                return ResourceManager.GetString("Menu_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change _Theme.
        /// </summary>
        public static string Menu_ChangeTheme {
            get {
                return ResourceManager.GetString("Menu_ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu _Clear Data.
        /// </summary>
        public static string Menu_ClearData {
            get {
                return ResourceManager.GetString("Menu_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu E_xit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu _Open.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu _Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save _As.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu _Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu _User Guide.
        /// </summary>
        public static string Menu_UserGuide {
            get {
                return ResourceManager.GetString("Menu_UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Actual State:.
        /// </summary>
        public static string Title_ActualState {
            get {
                return ResourceManager.GetString("Title_ActualState", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All Data Cleared.
        /// </summary>
        public static string TItle_AllDataCleared {
            get {
                return ResourceManager.GetString("TItle_AllDataCleared", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amount.
        /// </summary>
        public static string Title_Amount {
            get {
                return ResourceManager.GetString("Title_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category.
        /// </summary>
        public static string Title_Category {
            get {
                return ResourceManager.GetString("Title_Category", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Changes Saved.
        /// </summary>
        public static string Title_ChangesSaved {
            get {
                return ResourceManager.GetString("Title_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Created by Kacper Gumulak / Zorquan04.
        /// </summary>
        public static string Title_CreatedBy {
            get {
                return ResourceManager.GetString("Title_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expenses:.
        /// </summary>
        public static string Title_Expenses {
            get {
                return ResourceManager.GetString("Title_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Monthly Budget:.
        /// </summary>
        public static string Title_MonthlyBudget {
            get {
                return ResourceManager.GetString("Title_MonthlyBudget", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No.
        /// </summary>
        public static string Title_No {
            get {
                return ResourceManager.GetString("Title_No", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Remaining:.
        /// </summary>
        public static string Title_Remaining {
            get {
                return ResourceManager.GetString("Title_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Spent Last Week:.
        /// </summary>
        public static string Title_SpentLastWeek {
            get {
                return ResourceManager.GetString("Title_SpentLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Spent This Month:.
        /// </summary>
        public static string Title_SpentThisMonth {
            get {
                return ResourceManager.GetString("Title_SpentThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total: {0:N2} zł.
        /// </summary>
        public static string Title_Total {
            get {
                return ResourceManager.GetString("Title_Total", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Version.
        /// </summary>
        public static string Title_Version {
            get {
                return ResourceManager.GetString("Title_Version", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yes.
        /// </summary>
        public static string Title_Yes {
            get {
                return ResourceManager.GetString("Title_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu View application information.
        /// </summary>
        public static string Tooltip_About {
            get {
                return ResourceManager.GetString("Tooltip_About", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Switch between english and polish language.
        /// </summary>
        public static string Tooltip_ChangeLanguage {
            get {
                return ResourceManager.GetString("Tooltip_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Switch between light and dark theme.
        /// </summary>
        public static string Tooltip_ChangeTheme {
            get {
                return ResourceManager.GetString("Tooltip_ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Permanently remove all data.
        /// </summary>
        public static string Tooltip_ClearData {
            get {
                return ResourceManager.GetString("Tooltip_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close the application.
        /// </summary>
        public static string Tooltip_Exit {
            get {
                return ResourceManager.GetString("Tooltip_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open a CSV file with saved expenses and budget.
        /// </summary>
        public static string Tooltip_Open {
            get {
                return ResourceManager.GetString("Tooltip_Open", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save current data to file.
        /// </summary>
        public static string Tooltip_Save {
            get {
                return ResourceManager.GetString("Tooltip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save current data to a new file.
        /// </summary>
        public static string Tooltip_SaveAs {
            get {
                return ResourceManager.GetString("Tooltip_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open the user guide.
        /// </summary>
        public static string Tooltip_UserGuide {
            get {
                return ResourceManager.GetString("Tooltip_UserGuide", resourceCulture);
            }
        }
    }
}
